- name: Pull Docker Image on Localhost
  hosts: localhost
  connection: local
  become: true

  tasks:

    - name: Install Dependencies for Containerd
      yum:
        name: yum-utils
        state: present

    - name: Add Docker repository
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker Engine & Runtime
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Start & enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add remote "cloud-user" user to "do" group
      user:
        name: "cloud-user"
        groups: "docker"
        append: true
      tags:
        - docker

    - name: Adding GCloud CLI Repositories
      command: |
        sudo tee -a /etc/yum.repos.d/google-cloud-sdk.repo << EOM
        [google-cloud-cli]
        name=Google Cloud CLI
        baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el8-x86_64
        enabled=1
        gpgcheck=1
        repo_gpgcheck=0
        gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        EOM

    - name: Install GCloud CLI
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - google-cloud-cli

    - name: Authenticate GCloud and Pull Docker Images
      command: |
        gcloud auth activate-service-account --key-file=./iaac-devops-522507e929ea.json
        docker pull ${registryUrl}/react:production-latest

    - name: Docker Compose Up
      command: |
        echo imageTag=${metadata.IMAGE_TAG} > /metadata/.env
        docker-compose -f /metadata/docker-compose.yml up -d
